export const technologies = {
  backend: [
    {
      name: "Go",
      description: "Programming Language",
      icon: "/go.svg",
      color: "#61DAFB90",
      link: "https://go.dev/",
    },
    {
      name: "gRPC",
      description: "A high performance, open source universal RPC framework",
      icon: "/grpc.svg",
      color: "#61DAFB90",
      link: "https://grpc.io/",
    },
    {
      name: "Grafana",
      description: "Dashboard anything. Observe everything.",
      icon: "/grafana.svg",
      color: "#FC736290",
      link: "https://grafana.com/",
    },
    {
      name: "RabbitMQ",
      description: "Message broker",
      icon: "/rabbitmq.svg",
      color: "#FF736290",
      link: "https://www.rabbitmq.com/",
    },
    {
      name: "Prometheus",
      description: "Monitoring system",
      icon: "/prometheus.svg",
      color: "#FC736290",
      link: "https://prometheus.io/",
    },
    {
      name: "GraphQL",
      description: "Query Language",
      icon: "/graphql.png",
      color: "#E335A990",
      link: "https://graphql.org/",
    },
  ],
  devops: [
    {
      name: "Docker",
      description: "Containerization",
      icon: "/docker.webp",
      color: "#089CEB90",
      link: "https://www.docker.com/",
    },
    {
      name: "Nginx",
      description: "Web Server",
      icon: "/nginx.svg",
      color: "#00963990",
      link: "https://www.nginx.com/",
    },
  ],
  databases: [
    {
      name: "PostgreSQL",
      icon: "/postgres.webp",
      color: "#31679190",
      link: "https://www.postgresql.org/",
    },
    {
      name: "SQLite",
      icon: "/sqlite.png",
      color: "#43A3DC90",
      link: "https://www.sqlite.org/",
    },
    {
      name: "MySQL",
      icon: "/mysql.png",
      color: "#01618C90",
      link: "https://www.mysql.com/",
    },
    {
      name: "MongoDB",
      icon: "/mongo.webp",
      color: "#4CA94090",
      link: "https://www.mongodb.com/",
    },
    {
      name: "Firebase",
      icon: "/firebase.svg",
      color: "#FCCA3F90",
      link: "https://firebase.google.com/",
    },
    {
      name: "Redis",
      icon: "/redis.svg",
      color: "#C62F2C90",
      link: "https://redis.io/",
    },
    {
      name: "Elastic Search",
      icon: "/elasticsearch.svg",
      color: "#FCCA3F90",
      link: "https://www.elastic.co/",
    },
  ],
  android: [
    {
      name: "Kotlin",
      description: "Programming language",
      color: "#632180",
      link: "https://kotlinlang.org/",
      icon: "/kotlin.svg",
    },
    {
      name: "Java",
      description: "Programming language",
      color: "#213280",
      link: "https://www.java.com",
      icon: "/java.svg",
    },
    {
      name: "Jetpack Compose",
      icon: "/jetpackcompose.svg",
      color: "#218039",
      description: "Toolkit for building native UI",
      link: "https://developer.android.com/compose",
    },
  ],
};
